# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: "Setup Rust build"
description: "Common steps before running a Rust/Cargo task"

inputs:
    install-extra-tools:
        description: “Patterns to look in source files, comma separated”
        required: false
        default: "false"

runs:
    using: "composite"
    steps:
        - name: Setup CI caching
          # uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
          uses: WarpBuilds/rust-cache@e58c7440f25a26655b3867119bf68a1ba2dcc171 # v2.9.0
          with:
              save-if: ${{ github.ref == 'refs/heads/main' }}

        - name: Setup Rust and Cargo plugins
          shell: bash
          run: rustup show active-toolchain

        - name: Install additional tools (Mac-only)
          if:  ${{ runner.os == 'macOS' && inputs.install-extra-tools != 'false' }}
          shell: bash
          run: brew install coreutils

        - name: Install additional tools (Linux-only)
          if:  ${{ runner.os == 'Linux' && inputs.install-extra-tools != 'false' }}
          shell: bash
          run: sudo apt-get install -qy musl-dev musl-tools binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu
