# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

pull_request_rules:
  - name: Automatic merges for Renovate pull requests
    conditions:
      - author~=^renovate\[bot\]$
      - check-success=all-checks
      - check-success=dogfood-docker
      - check-success=dogfood-rust
    actions:
      review:
        type: APPROVE
      merge:
        method: squash

  - name: Be author's friend
    conditions:
      - author~=^ubiratansoares
      - check-success=all-checks
      - check-success=dogfood-docker
      - check-success=dogfood-rust
    actions:
      review:
        type: APPROVE
      merge:
        method: squash
