#! /usr/bin/env bash
# Copyright 2024 Dotanuki Labs
# SPDX-License-Identifier: MIT

set -e

usage() {
    echo
    echo "Available tasks:"
    echo
    echo "setup      # Installs required Cargo extensions"
    echo "lint       # Check code formatting and smells"
    echo "tests      # Run tests for Rust modules and integration tests"
    echo "assemble   # Builds binaries according to the environment (local or CI)"
    echo "security   # Run security checks and generates supply-chain artifacts"
    echo
}

install_cargo_extensions() {
    if [[ -z "$CI" ]]; then
        cargo install cargo-nextest@0.9.72 --force
    fi

    cargo install cargo-deny@0.14.24 --force
    cargo install cargo-cyclonedx@0.5.3 --force
    cargo install cargo-msrv@0.15.1 --force
}

check_code_smells() {
    echo
    echo "🦀 Checking code formatting (rustfmt)"
    echo
    cargo fmt --check

    echo
    echo "🦀 Checking code smells (clippy)"
    echo
    cargo clippy --all-targets --all-features -- -D warnings -W clippy::unwrap_used
    echo
}

run_cargo_tests() {
    echo

    if [[ -z "$CI" ]]; then
        echo "🦀 Running tests from Rust code (test runner : nextest)"
        echo
        cargo nextest run
    else
        echo "🦀 Running tests from Rust code (test runner : default)"
        echo
        cargo test
    fi

    echo
}

build_binaries() {
    echo
    echo "🦀  Building project according to environment"
    echo
    ./scripts/flex-build.sh
    echo
}

check_supply_chain() {
    echo
    echo "🦀 Checking minimum supported Rust version (MSRV)"
    echo
    cargo msrv verify

    echo
    echo "🦀 Enforcing rules over Cargo dependencies"
    echo
    cargo deny check

    echo
    echo "🦀 Generating SBOMs"
    echo
    cargo cyclonedx --format json
    echo
}

readonly task="$1"
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$dir"

if [[ -z "$task" ]]; then
    usage
    exit 0
fi

case "$task" in
"setup")
    install_cargo_extensions
    ;;
"lint")
    check_code_smells
    ;;
"msrv")
    check_msrv
    ;;
"tests")
    run_cargo_tests
    ;;
"assemble")
    build_binaries
    ;;
"security")
    check_supply_chain
    ;;
*)
    echo "Error: unsupported task → $task"
    usage
    exit 1
    ;;
esac
