#! /usr/bin/env bash
# Copyright 2024 Dotanuki Labs
# SPDX-License-Identifier: MIT

set -e

usage() {
    echo
    echo "Available tasks:"
    echo
    echo "setup      # Installs required Cargo extensions"
    echo "lint       # Check code formatting and smells"
    echo "tests      # Run tests for Rust modules and integration tests"
    echo "assemble   # Builds binaries according to the environment (local or CI)"
    echo "security   # Run security checks and generates supply-chain artifacts"
    echo
}

install_cargo_extensions() {
    echo
    echo "🦀 Installing cargo-binstall"
    ./scripts/cargo-binstaller.sh

    echo
    echo "🦀 Installing cargo-nextest"
    cargo binstall cargo-nextest@0.9.72 --no-confirm --force --quiet

    echo
    echo "🦀 Installing cargo-deny"
    cargo binstall cargo-deny@0.14.24 --no-confirm --force --quiet

    echo
    echo "🦀 Installing cargo-cyclonedx"
    cargo binstall cargo-cyclonedx@0.5.2 --no-confirm --force --quiet

    echo
    echo "🦀 Installing cargo-msrv"
    cargo binstall cargo-msrv@0.15.1 --no-confirm --force --quiet

    echo
    echo "🦀 Installing cargo-get"
    cargo binstall cargo-get@1.1.1 --no-confirm --force --quiet

    echo
}

check_code_smells() {
    echo
    echo "🦀 Checking code formatting (rustfmt)"
    echo
    cargo fmt --check

    echo
    echo "🦀 Checking code smells (clippy)"
    echo
    cargo clippy --all-targets --all-features -- -D warnings -W clippy::unwrap_used
    echo
}

run_cargo_tests() {
    echo
    echo "🦀 Running unit + integration tests for Rust code"
    echo
    cargo nextest run
    echo
}

build_binaries() {
    echo
    echo "🦀 Building project according to environment"
    echo
    ./scripts/flex-build.sh
    echo
}

check_supply_chain() {
    echo
    echo "🦀 Checking minimum supported Rust version (MSRV)"
    echo
    cargo msrv verify

    echo
    echo "🦀 Enforcing rules over Cargo dependencies"
    echo
    cargo deny check

    echo
    echo "🦀 Generating SBOMs"
    echo
    cargo cyclonedx --format json
    echo
}

readonly task="$1"
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$dir"

if [[ -z "$task" ]]; then
    usage
    exit 0
fi

case "$task" in
"setup")
    install_cargo_extensions
    ;;
"lint")
    check_code_smells
    ;;
    ;;
"tests")
    run_cargo_tests
    ;;
"assemble")
    build_binaries
    ;;
"security")
    check_supply_chain
    ;;
*)
    echo "Error: unsupported task → $task"
    usage
    exit 1
    ;;
esac
