# Copyright 2025 Dotanuki Labs
# SPDX-License-Identifier: MIT

name: ci-docs

on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint-build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Project checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Lint Markdown files
        uses: rvben/rumdl@ce2ee387fc15da333da08f395dc578d5eb5e29b7 # v0.1.53

      - name: Build and archive documentation assets
        uses: dotanuki-labs/github-actions/foss/prepare-ghpages@6a40acb36b6d9918b5de15b74b3473af850204a7
